### ISSUE TITLE
Test run of the HawkEDA tool

### ISSUE THREAD

**Issue by kct949** [otter-diku/simulation-framework-for-microservices#3]

**Comment by PTheyssen** [comment]
Right now it seems like the fork for HawkEDA cannot be build (it uses dotnet version 5) (but there might be an easy fix), otherwise we might have to manually remove the identity service from the current eShop repository to run HawkEDA against it, generally the application might have evolved since then (2 years)

**Comment by kct949** [comment]
we dont see too much value in running this locally, closing the ticket for now
